import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { APP_NAME } from '@/utils'
import LandingPage from './Landingpage'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>{APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage />
    </>
  )
}
